
version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"  # 

  fastapi:
    build: .
    container_name: fastapi_new
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
