apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: student-companion-dataprep-deployment
  name: student-companion-dataprep-deployment
  namespace: student-companion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: student-companion-dataprep-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: student-companion-dataprep-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-wyn02
      containers:
        - env:
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HUGGINGFACEHUB_API_TOKEN
              value: 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
            - name: LLM_SERVER_HOST_IP
              value: g2-wyn02.iind.intel.com
            - name: LLM_SERVER_PORT
              value: "31025"
            - name: LLM_SERVER_PORT
              value: "31025"
            - name: LLM_MODEL_ID
              value: "meta-llama/Meta-Llama-3.1-8B-Instruct"
            - name: LLM_USE_MODEL_PARAM
              value: "true"
            - name: LOGFLAG
              value: "true"
            - name: REDIS_URL
              value: redis://student-companion-redis-deployment:6321
            - name: TEI_EMBEDDING_ENDPOINT
              value: http://student-companion-tei-embedding-deployment:6020
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,student-companion-redis-deployment,student-companion-groq-deployment
          image: navchetna/dataprep:latest
          name: student-companion-dataprep-container
          ports:
            - containerPort: 6009
              protocol: TCP
          volumeMounts:
            - mountPath: ~/.cache/huggingface/hub
              name: student-companion-tei-reranking-claim0
      restartPolicy: Always
      volumes:
        - name: student-companion-tei-reranking-claim0
          hostPath:
            path: /mnt/hf_cache
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: student-companion-dataprep-deployment
  name: student-companion-dataprep-deployment
  namespace: student-companion
spec:
  type: NodePort
  ports:
    - name: "5099"
      port: 5099
      protocol: TCP
      targetPort: 6007
  selector:
    io.kompose.service: student-companion-dataprep-deployment
