apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: student-companion-tei-embedding-deployment
  name: student-companion-tei-embedding-deployment
  namespace: student-companion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: student-companion-tei-embedding-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: student-companion-tei-embedding-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-wyn02
      containers:
        - args:
            - --model-id
            - BAAI/bge-base-en-v1.5
            - --auto-truncate
          env:
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com
          image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
          name: student-companion-tei-embedding-container
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: ~/.cache/huggingface/hub
              name: student-companion-tei-reranking-claim0
      restartPolicy: Always
      volumes:
        - name: student-companion-tei-reranking-claim0
          hostPath:
            path: /mnt/hf_cache
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: student-companion-tei-embedding-deployment
  name: student-companion-tei-embedding-deployment
  namespace: student-companion
spec:
  type: ClusterIP
  ports:
    - name: "6020"
      port: 6020
      protocol: TCP
      targetPort: 80
  selector:
    io.kompose.service: student-companion-tei-embedding-deployment