apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: research-assistant-mongodb-deployment
  name: research-assistant-mongodb-deployment
  namespace: research-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: research-assistant-mongodb-deployment
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: research-assistant-mongodb-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-wyn02
      containers:
        - image: mongo
          name: research-assistant-mongodb-container
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: research-assistant-mongodb-deployment
  name: research-assistant-mongodb-deployment
  namespace: research-assistant
spec:
  type: NodePort
  ports:
    - name: "27027"
      port: 27027
      protocol: TCP
      targetPort: 27017
      nodePort: 30103
  selector:
    io.kompose.service: research-assistant-mongodb-deployment