apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: research-assistant-ui-deployment
  name: research-assistant-ui-deployment
  namespace: research-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: research-assistant-ui-deployment
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: research-assistant-ui-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-wyn02
      containers:
        - image: navchetna/research-agent-ui:gaudi2
          name: research-assistant-ui-container
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: research-assistant-ui-deployment
  name: research-assistant-ui-deployment
  namespace: research-assistant
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30108
  selector:
    io.kompose.service: research-assistant-ui-deployment
